/** Florian brand tokens — quotation suite */
export const BRAND = {
  name: "Florian",
  shortName: "Florian",
  tagline: "Quality that you can trust",
  coverTagline: "Sales. Quotes. Trade.",
  heroLine1: "QUALITY THAT",
  heroLine2: "YOU CAN",
  heroLine3: "TRUST.",
  heroSub: "Sales pipeline, quotations, and partner trade.",
  quotationLabel: "B2B SUPPLY",
  quotationTitle: "QUOTATION",
  quotationTagline: "Quotations for Florian partners.",
  appName: "Florian — Quotations",
  poweredBy: "Powered by Dyzen Solar Technologies",
  logo: {
    primary: "/brand/logo.jpeg",
    width: 1024,
    height: 1024,
    icon: "/brand/logo.jpeg",
    iconWidth: 64,
    iconHeight: 64,
    login: "/brand/logo.jpeg",
    loginWidth: 120,
    loginHeight: 120,
    watermark: "/brand/logo.jpeg",
    coverHome: "/brand/cover-home.jpg",
    nonSolarCover: "/brand/non-solar-cover.jpg",
    paymentQr: "/brand/logo.jpeg",
  },
  bank: {
    accountName: "FLORIAN",
    bankName: "",
    accountNumber: "",
    ifscCode: "",
    accountType: "CURRENT A/C",
    branch: "",
  },
  contact: {
    address: "",
    phone: "",
    email: "",
    website: "",
    branches: [] as { label: string; address: string }[],
  },
  colors: {
    blue: "#163A5C",
    navy: "#163A5C",
    orange: "#1BA8E0",
    grey: "#64748B",
    black: "#163A5C",
    softBlue: "#E4F5FC",
    headingBlue: "#163A5C",
    yellow: "#1BA8E0",
    green: "#1B7A4A",
  },
  benefits: [
    { label: "Lower Electricity Bills", tone: "blue" },
    { label: "High Performance Solar Systems", tone: "orange" },
    { label: "Clean & Green Energy", tone: "green" },
    { label: "Reliable & Durable", tone: "navy" },
    { label: "Save More with Subsidy", tone: "indigo" },
    { label: "Quality You Can Trust", tone: "olive" },
  ],
  services: [
    { title: "DESIGN", sub: "Smart & Efficient" },
    { title: "SUPPLY", sub: "Quality Assured" },
    { title: "INSTALLATION", sub: "Safe & Reliable" },
    { title: "COMMISSIONING", sub: "Performance Guaranteed" },
  ],
} as const;

/** Cyan scale from the Florian drop */
export const BRAND_PALETTE = {
  orange: {
    50: "#F4FBFE",
    100: "#E4F5FC",
    200: "#C5EAF8",
    300: "#8FD4F2",
    400: "#4FBFEB",
    500: "#1BA8E0",
    600: "#1489C4",
    700: "#0F6E9E",
    800: "#163A5C",
    900: "#0E2438",
  },
} as const;
