/** Recare LMS authority catalog — keys match supabase/migrations/002_lms.sql */

export const AUTHORITY_GROUPS = {
  general: "Team & Access",
  sales: "Lead Management",
  accounts: "Accounts",
  documentation: "Documentation",
  installation: "Installation",
} as const;

export type AuthorityGroup = keyof typeof AUTHORITY_GROUPS;

export const AUTHORITIES = [
  {
    key: "full_access",
    label: "Full Access",
    description: "Unrestricted access across Florian",
    group: "general" as const,
  },
  {
    key: "manage_users",
    label: "Manage Team",
    description: "Add, edit, and deactivate team members",
    group: "general" as const,
  },
  {
    key: "manage_roles",
    label: "Manage Roles & Permissions",
    description: "Create roles and change what each role can do",
    group: "general" as const,
  },
  {
    key: "manage_settings",
    label: "Manage Settings",
    description: "Change company settings",
    group: "general" as const,
  },
  {
    key: "import_leads",
    label: "Import Leads (Excel)",
    description: "Upload leads from Excel spreadsheets",
    group: "sales" as const,
  },
  {
    key: "distribute_leads",
    label: "Distribute Leads",
    description: "Assign imported leads to tele-callers or surveyors",
    group: "sales" as const,
  },
  {
    key: "add_edit_leads",
    label: "Add / Edit Leads",
    description: "Create and update lead contact details",
    group: "sales" as const,
  },
  {
    key: "delete_leads",
    label: "Delete Leads (Owner)",
    description: "Permanently delete leads and related records — Owner only",
    group: "sales" as const,
  },
  {
    key: "move_lead_stage",
    label: "Move Lead Stage",
    description: "Advance or move leads on the pipeline",
    group: "sales" as const,
  },
  {
    key: "reassign_leads",
    label: "Reassign Leads",
    description: "Move leads between team members; allows backward pipeline moves",
    group: "sales" as const,
  },
  {
    key: "reopen_lost_leads",
    label: "Reopen Lost Leads",
    description: "Restore lost leads back to the active pipeline",
    group: "sales" as const,
  },
  {
    key: "view_all_leads",
    label: "View All Leads",
    description: "See every lead in the company, not just ones assigned to you",
    group: "sales" as const,
  },
  {
    key: "log_sales_activity",
    label: "Log Sales Activity",
    description: "Log calls, visits, and follow-ups on leads",
    group: "sales" as const,
  },
  {
    key: "schedule_site_visit",
    label: "Schedule Site Visit",
    description: "Book survey visits and assign field slots",
    group: "sales" as const,
  },
  {
    key: "conduct_survey",
    label: "Complete digital survey",
    description: "Open the digital survey form and mark Survey Done.",
    group: "sales" as const,
  },
  {
    key: "view_quotations",
    label: "View Quotations",
    description: "View solar and general quotations",
    group: "sales" as const,
  },
  {
    key: "create_quotations",
    label: "Create Quotations",
    description: "Create and edit draft quotations",
    group: "sales" as const,
  },
  {
    key: "manage_quotations",
    label: "Manage Quotations",
    description: "Full quotation management including delete",
    group: "sales" as const,
  },
  {
    key: "edit_quotation_pricing",
    label: "Edit Quotation Pricing",
    description: "Apply discounts and price overrides",
    group: "sales" as const,
  },
  {
    key: "accept_quotations",
    label: "Accept Quotations",
    description: "Mark quotations accepted and advance lead stage",
    group: "sales" as const,
  },
  {
    key: "manage_catalog_items",
    label: "Manage Catalog Items",
    description: "Maintain quotation catalog brands and items",
    group: "sales" as const,
  },
  {
    key: "view_trade_ledger",
    label: "View Trade Ledger",
    description: "Open account outward / inward / summary",
    group: "accounts" as const,
  },
  {
    key: "log_trade_outward",
    label: "Log Outward Trade",
    description: "Log goods we supplied and attach Sales invoices / GR",
    group: "accounts" as const,
  },
  {
    key: "log_trade_inward",
    label: "Log Inward Trade",
    description: "Log goods we received and attach vendor bills",
    group: "accounts" as const,
  },
  {
    key: "manage_trade_skus",
    label: "Manage Trade SKUs",
    description: "Maintain outward and inward line types",
    group: "accounts" as const,
  },
  {
    key: "view_profit",
    label: "View Profit and Loss",
    description: "Open company sales, purchases, and gross profit",
    group: "accounts" as const,
  },
  {
    key: "record_payment",
    label: "Record Payment",
    description: "Enter token / pre-dispatch / final payment details",
    group: "accounts" as const,
  },
  {
    key: "verify_payment",
    label: "Verify Payment",
    description: "Accounts: verify txn ID, date, and bank credit",
    group: "accounts" as const,
  },
  {
    key: "upload_feasibility_report",
    label: "Upload Feasibility Report",
    description: "Upload the pre-install grid feasibility PDF after Won",
    group: "documentation" as const,
  },
  {
    key: "approve_feasibility_report",
    label: "Approve Feasibility Report",
    description: "Approve or reject feasibility reports",
    group: "documentation" as const,
  },
  {
    key: "view_payment_queues",
    label: "View Payment Queues",
    description: "Open Accounts and Feasibility work queues",
    group: "accounts" as const,
  },
  {
    key: "assign_installation_crew",
    label: "Assign Installation Crew",
    description: "Owner assigns installation crew after pre-dispatch is verified",
    group: "installation" as const,
  },
  {
    key: "upload_installation_proofs",
    label: "Upload Installation Proofs",
    description: "Upload site / overview installation photos",
    group: "installation" as const,
  },
  {
    key: "upload_panel_barcodes",
    label: "Upload Panel Barcodes",
    description: "Upload panel barcode / DCR serial photos",
    group: "installation" as const,
  },
  {
    key: "complete_installation",
    label: "Complete Installation",
    description: "Mark installation complete and notify teams",
    group: "installation" as const,
  },
  {
    key: "view_installation_queue",
    label: "View Installation Queue",
    description: "Open installation assignment and crew queues",
    group: "installation" as const,
  },
  {
    key: "manage_liaison",
    label: "Manage Liaison Queue",
    description: "Work Discom meter and subsidy follow-ups",
    group: "documentation" as const,
  },
  {
    key: "mark_meter_installed",
    label: "Mark Meter Installed",
    description: "Staff override for meter installed (customer portal preferred)",
    group: "documentation" as const,
  },
  {
    key: "mark_subsidy_received",
    label: "Mark Subsidy Received",
    description: "Staff assist marking subsidy received",
    group: "documentation" as const,
  },
  {
    key: "verify_subsidy",
    label: "Verify Subsidy Payment",
    description: "Accounts verifies subsidy bank credit and issues certificate",
    group: "accounts" as const,
  },
  {
    key: "manage_portal_documents",
    label: "Manage Portal Documents",
    description: "Upload invoices and declarations visible in customer portal",
    group: "documentation" as const,
  },
  {
    key: "view_customer_portal_admin",
    label: "View Portal Admin",
    description: "See portal codes and customer-facing project status",
    group: "documentation" as const,
  },
  {
    key: "view_service_tickets",
    label: "View Service Tickets",
    description: "Open maintenance ticket queues",
    group: "sales" as const,
  },
  {
    key: "accept_service_ticket",
    label: "Accept Service Ticket",
    description: "Claim a raised maintenance ticket (first accept wins)",
    group: "sales" as const,
  },
  {
    key: "resolve_service_ticket",
    label: "Resolve Service Ticket",
    description: "Work and close tickets with proof photos",
    group: "sales" as const,
  },
  {
    key: "force_assign_service_ticket",
    label: "Force Assign Service Ticket",
    description: "Supervisor assigns an engineer when unclaimed or rejected",
    group: "sales" as const,
  },
  {
    key: "enqueue_cleaning_reminders",
    label: "Enqueue Cleaning Reminders",
    description: "Queue 15-day panel cleaning + referral nudges",
    group: "sales" as const,
  },
  {
    key: "view_grievances",
    label: "View Grievances",
    description: "Open internal company grievance queue",
    group: "general" as const,
  },
  {
    key: "raise_grievance",
    label: "Raise Grievance",
    description: "File an internal company issue",
    group: "general" as const,
  },
  {
    key: "escalate_grievance",
    label: "Escalate Grievance",
    description: "Escalate and reassign internal grievances",
    group: "general" as const,
  },
  {
    key: "resolve_grievance",
    label: "Resolve Grievance",
    description: "Mark internal grievances resolved",
    group: "general" as const,
  },
  {
    key: "submit_dealer_commission",
    label: "Submit Dealer Commission",
    description: "Submit commission amount/% on a completed dealer file",
    group: "accounts" as const,
  },
  {
    key: "approve_dealer_commission",
    label: "Approve Dealer Commission",
    description: "Accounts approve or reject dealer commission forms",
    group: "accounts" as const,
  },
  {
    key: "assign_dealer",
    label: "Assign Dealer",
    description: "Link a dealer profile to a lead / file",
    group: "sales" as const,
  },
  {
    key: "view_reports",
    label: "View Reports",
    description: "Open sales and operations reports",
    group: "general" as const,
  },
] as const;

export type AuthorityKey = (typeof AUTHORITIES)[number]["key"];

export const AUTHORITY_KEYS = AUTHORITIES.map((a) => a.key) as AuthorityKey[];

/** Defaults when role_authorities / user_authorities are empty — mirrors migration seeds. */
export const DEFAULT_ROLE_AUTHORITIES: Record<string, AuthorityKey[]> = {
  admin: AUTHORITY_KEYS,
  sales_manager: [
    "view_all_leads",
    "import_leads",
    "distribute_leads",
    "add_edit_leads",
    "move_lead_stage",
    "reassign_leads",
    "reopen_lost_leads",
    "log_sales_activity",
    "schedule_site_visit",
    "conduct_survey",
    "view_quotations",
    "create_quotations",
    "manage_quotations",
    "edit_quotation_pricing",
    "accept_quotations",
    "manage_catalog_items",
    "record_payment",
    "view_payment_queues",
    "upload_feasibility_report",
    "view_reports",
    "manage_users",
    "view_grievances",
    "raise_grievance",
    "escalate_grievance",
    "resolve_grievance",
    "submit_dealer_commission",
    "approve_dealer_commission",
    "assign_dealer",
    "view_trade_ledger",
    "log_trade_outward",
    "log_trade_inward",
    "manage_trade_skus",
  ],
  sales_executive: [
    "add_edit_leads",
    "move_lead_stage",
    "log_sales_activity",
    "conduct_survey",
    "view_quotations",
    "create_quotations",
    "edit_quotation_pricing",
    "accept_quotations",
    "record_payment",
    "view_payment_queues",
    "view_grievances",
    "raise_grievance",
    "view_trade_ledger",
    "log_trade_outward",
  ],
  feasibility: [
    "upload_feasibility_report",
    "view_payment_queues",
    "view_grievances",
    "raise_grievance",
  ],
  ops_coordinator: [
    "assign_installation_crew",
    "upload_installation_proofs",
    "upload_panel_barcodes",
    "complete_installation",
    "view_installation_queue",
    "view_grievances",
    "raise_grievance",
  ],
  installation_crew: [
    "upload_installation_proofs",
    "upload_panel_barcodes",
    "complete_installation",
    "view_installation_queue",
    "view_grievances",
    "raise_grievance",
  ],
  liaison: [
    "manage_liaison",
    "upload_feasibility_report",
    "mark_meter_installed",
    "mark_subsidy_received",
    "manage_portal_documents",
    "view_customer_portal_admin",
    "view_grievances",
    "raise_grievance",
  ],
  accounts: [
    "view_quotations",
    "record_payment",
    "verify_payment",
    "view_payment_queues",
    "verify_subsidy",
    "view_customer_portal_admin",
    "view_grievances",
    "raise_grievance",
    "submit_dealer_commission",
    "approve_dealer_commission",
    "view_trade_ledger",
    "log_trade_inward",
    "view_profit",
  ],
  tele_caller: [
    "add_edit_leads",
    "move_lead_stage",
    "log_sales_activity",
    "schedule_site_visit",
    "view_quotations",
    "view_grievances",
    "raise_grievance",
    "view_trade_ledger",
    "log_trade_outward",
  ],
  surveyor: [
    "conduct_survey",
    "log_sales_activity",
    "move_lead_stage",
    "view_quotations",
    "view_grievances",
    "raise_grievance",
  ],
  service_engineer: [
    "view_service_tickets",
    "accept_service_ticket",
    "resolve_service_ticket",
    "view_grievances",
    "raise_grievance",
  ],
  service_supervisor: [
    "view_service_tickets",
    "accept_service_ticket",
    "resolve_service_ticket",
    "force_assign_service_ticket",
    "enqueue_cleaning_reminders",
    "view_grievances",
    "raise_grievance",
  ],
  dealer: [
    "add_edit_leads",
    "log_sales_activity",
    "view_quotations",
    "submit_dealer_commission",
    "view_grievances",
    "raise_grievance",
  ],
};
